create table ICD_Enrollment (
	enrollmentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	selectedEntityType VARCHAR(75) null,
	organizationNPINum VARCHAR(75) null,
	organizationName VARCHAR(75) null,
	organizationAddress1 VARCHAR(75) null,
	organizationAddress2 VARCHAR(75) null,
	organizationCity VARCHAR(75) null,
	organizationPhone VARCHAR(75) null,
	top5HealthPlansByRev VARCHAR(75) null,
	clearinghouses VARCHAR(75) null,
	ehrBillingVendors VARCHAR(75) null,
	revCycleVendors VARCHAR(75) null,
	top5DrgByRev VARCHAR(75) null,
	icd9Drg1 VARCHAR(75) null,
	icd9Drg2 VARCHAR(75) null,
	icd9Drg3 VARCHAR(75) null,
	icd9Drg4 VARCHAR(75) null,
	icd9Drg5 VARCHAR(75) null,
	top5Icd9ByRev VARCHAR(75) null,
	icd9Dx1 VARCHAR(75) null,
	icd9Dx2 VARCHAR(75) null,
	icd9Dx3 VARCHAR(75) null,
	icd9Dx4 VARCHAR(75) null,
	icd9Dx5 VARCHAR(75) null,
	primaryTestingContact VARCHAR(75) null,
	primaryTestingContactTitle VARCHAR(75) null,
	primaryTestingContactPhone VARCHAR(75) null,
	primaryTestingContactEmail VARCHAR(75) null,
	primaryCodingContact VARCHAR(75) null,
	primaryCodingContactTitle VARCHAR(75) null,
	primaryCodingContactPhone VARCHAR(75) null,
	primaryCodingContactEmail VARCHAR(75) null,
	primaryBillingContact VARCHAR(75) null,
	primaryBillingContactTitle VARCHAR(75) null,
	primaryBillingContactPhone VARCHAR(75) null,
	primaryBillingContactEmail VARCHAR(75) null,
	file VARCHAR(75) null
);

create table ICD_MedicalRecord (
	mrId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	mrTestCaseName VARCHAR(75) null,
	msDrg VARCHAR(75) null,
	patientType VARCHAR(75) null,
	patientAge VARCHAR(75) null,
	los VARCHAR(75) null,
	ahrqCategoryCode VARCHAR(75) null,
	ahrqSubCategoryCode VARCHAR(75) null,
	mrTestCaseDescription VARCHAR(75) null,
	icd9AdmittingDx VARCHAR(75) null,
	icd9PrincipalDx VARCHAR(75) null,
	icd9PrincipalProcedure VARCHAR(75) null,
	otherIcd9Dx1 VARCHAR(75) null,
	otherIcd9Dx2 VARCHAR(75) null,
	otherIcd9Dx3 VARCHAR(75) null,
	otherIcd9Pcs1 VARCHAR(75) null,
	otherIcd9Pcs2 VARCHAR(75) null,
	otherIcd9Pcs3 VARCHAR(75) null,
	icd10AdmittingDx VARCHAR(75) null,
	icd10PrincipalDx VARCHAR(75) null,
	icd10PrincipalProcedure VARCHAR(75) null,
	otherIcd10Dx1 VARCHAR(75) null,
	otherIcd10Dx2 VARCHAR(75) null,
	otherIcd10Dx3 VARCHAR(75) null,
	otherIcd10Pcs1 VARCHAR(75) null,
	otherIcd10Pcs2 VARCHAR(75) null,
	otherIcd10Pcs3 VARCHAR(75) null,
	isHistoryAndPsysical BOOLEAN,
	isDischargeNotes BOOLEAN,
	isConsultations BOOLEAN,
	isOperatingNotes BOOLEAN,
	isPhysicianNotes BOOLEAN,
	isRadiology BOOLEAN,
	isGiProcedures BOOLEAN,
	isEducationalNotes BOOLEAN,
	file VARCHAR(75) null
);

create table ICD_MrAd (
	mrId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	selectedEntityType VARCHAR(75) null
);

create table ICD_References (
	referencesId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	referencesName VARCHAR(75) null,
	key_ VARCHAR(75) null,
	value VARCHAR(75) null,
	active_ VARCHAR(75) null
);