create table ICD_Enrollment (
	enrollmentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	selectedEntityType VARCHAR(75) null,
	organizationNPINum VARCHAR(75) null,
	organizationName VARCHAR(75) null,
	organizationAddress1 VARCHAR(75) null,
	organizationAddress2 VARCHAR(75) null,
	organizationCity VARCHAR(75) null,
	organizationPhone VARCHAR(75) null,
	top5HealthPlansByRev VARCHAR(75) null,
	clearinghouses VARCHAR(75) null,
	ehrBillingVendors VARCHAR(75) null,
	revCycleVendors VARCHAR(75) null,
	top5DrgByRev VARCHAR(75) null,
	icd9Drg1 VARCHAR(75) null,
	icd9Drg2 VARCHAR(75) null,
	icd9Drg3 VARCHAR(75) null,
	icd9Drg4 VARCHAR(75) null,
	icd9Drg5 VARCHAR(75) null,
	top5Icd9ByRev VARCHAR(75) null,
	icd9Dx1 VARCHAR(75) null,
	icd9Dx2 VARCHAR(75) null,
	icd9Dx3 VARCHAR(75) null,
	icd9Dx4 VARCHAR(75) null,
	icd9Dx5 VARCHAR(75) null,
	primaryTestingContact VARCHAR(75) null,
	primaryTestingContactTitle VARCHAR(75) null,
	primaryTestingContactPhone VARCHAR(75) null,
	primaryTestingContactEmail VARCHAR(75) null,
	primaryCodingContact VARCHAR(75) null,
	primaryCodingContactTitle VARCHAR(75) null,
	primaryCodingContactPhone VARCHAR(75) null,
	primaryCodingContactEmail VARCHAR(75) null,
	primaryBillingContact VARCHAR(75) null,
	primaryBillingContactTitle VARCHAR(75) null,
	primaryBillingContactPhone VARCHAR(75) null,
	primaryBillingContactEmail VARCHAR(75) null,
	file VARCHAR(75) null
);