/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.virtusa.icd.service.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Enrollment service. Represents a row in the &quot;ICD_Enrollment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.virtusa.icd.service.builder.model.impl.EnrollmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.virtusa.icd.service.builder.model.impl.EnrollmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Enrollment
 * @see com.virtusa.icd.service.builder.model.impl.EnrollmentImpl
 * @see com.virtusa.icd.service.builder.model.impl.EnrollmentModelImpl
 * @generated
 */
public interface EnrollmentModel extends BaseModel<Enrollment>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a enrollment model instance should use the {@link Enrollment} interface instead.
	 */

	/**
	 * Returns the primary key of this enrollment.
	 *
	 * @return the primary key of this enrollment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this enrollment.
	 *
	 * @param primaryKey the primary key of this enrollment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the enrollment ID of this enrollment.
	 *
	 * @return the enrollment ID of this enrollment
	 */
	public long getEnrollmentId();

	/**
	 * Sets the enrollment ID of this enrollment.
	 *
	 * @param enrollmentId the enrollment ID of this enrollment
	 */
	public void setEnrollmentId(long enrollmentId);

	/**
	 * Returns the group ID of this enrollment.
	 *
	 * @return the group ID of this enrollment
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this enrollment.
	 *
	 * @param groupId the group ID of this enrollment
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this enrollment.
	 *
	 * @return the company ID of this enrollment
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this enrollment.
	 *
	 * @param companyId the company ID of this enrollment
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this enrollment.
	 *
	 * @return the user ID of this enrollment
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this enrollment.
	 *
	 * @param userId the user ID of this enrollment
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this enrollment.
	 *
	 * @return the user uuid of this enrollment
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this enrollment.
	 *
	 * @param userUuid the user uuid of this enrollment
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this enrollment.
	 *
	 * @return the user name of this enrollment
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this enrollment.
	 *
	 * @param userName the user name of this enrollment
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this enrollment.
	 *
	 * @return the create date of this enrollment
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this enrollment.
	 *
	 * @param createDate the create date of this enrollment
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this enrollment.
	 *
	 * @return the modified date of this enrollment
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this enrollment.
	 *
	 * @param modifiedDate the modified date of this enrollment
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the selected entity type of this enrollment.
	 *
	 * @return the selected entity type of this enrollment
	 */
	@AutoEscape
	public String getSelectedEntityType();

	/**
	 * Sets the selected entity type of this enrollment.
	 *
	 * @param selectedEntityType the selected entity type of this enrollment
	 */
	public void setSelectedEntityType(String selectedEntityType);

	/**
	 * Returns the organization n p i num of this enrollment.
	 *
	 * @return the organization n p i num of this enrollment
	 */
	@AutoEscape
	public String getOrganizationNPINum();

	/**
	 * Sets the organization n p i num of this enrollment.
	 *
	 * @param organizationNPINum the organization n p i num of this enrollment
	 */
	public void setOrganizationNPINum(String organizationNPINum);

	/**
	 * Returns the organization name of this enrollment.
	 *
	 * @return the organization name of this enrollment
	 */
	@AutoEscape
	public String getOrganizationName();

	/**
	 * Sets the organization name of this enrollment.
	 *
	 * @param organizationName the organization name of this enrollment
	 */
	public void setOrganizationName(String organizationName);

	/**
	 * Returns the organization address1 of this enrollment.
	 *
	 * @return the organization address1 of this enrollment
	 */
	@AutoEscape
	public String getOrganizationAddress1();

	/**
	 * Sets the organization address1 of this enrollment.
	 *
	 * @param organizationAddress1 the organization address1 of this enrollment
	 */
	public void setOrganizationAddress1(String organizationAddress1);

	/**
	 * Returns the organization address2 of this enrollment.
	 *
	 * @return the organization address2 of this enrollment
	 */
	@AutoEscape
	public String getOrganizationAddress2();

	/**
	 * Sets the organization address2 of this enrollment.
	 *
	 * @param organizationAddress2 the organization address2 of this enrollment
	 */
	public void setOrganizationAddress2(String organizationAddress2);

	/**
	 * Returns the organization city of this enrollment.
	 *
	 * @return the organization city of this enrollment
	 */
	@AutoEscape
	public String getOrganizationCity();

	/**
	 * Sets the organization city of this enrollment.
	 *
	 * @param organizationCity the organization city of this enrollment
	 */
	public void setOrganizationCity(String organizationCity);

	/**
	 * Returns the organization phone of this enrollment.
	 *
	 * @return the organization phone of this enrollment
	 */
	@AutoEscape
	public String getOrganizationPhone();

	/**
	 * Sets the organization phone of this enrollment.
	 *
	 * @param organizationPhone the organization phone of this enrollment
	 */
	public void setOrganizationPhone(String organizationPhone);

	/**
	 * Returns the top5 health plans by rev of this enrollment.
	 *
	 * @return the top5 health plans by rev of this enrollment
	 */
	@AutoEscape
	public String getTop5HealthPlansByRev();

	/**
	 * Sets the top5 health plans by rev of this enrollment.
	 *
	 * @param top5HealthPlansByRev the top5 health plans by rev of this enrollment
	 */
	public void setTop5HealthPlansByRev(String top5HealthPlansByRev);

	/**
	 * Returns the clearinghouses of this enrollment.
	 *
	 * @return the clearinghouses of this enrollment
	 */
	@AutoEscape
	public String getClearinghouses();

	/**
	 * Sets the clearinghouses of this enrollment.
	 *
	 * @param clearinghouses the clearinghouses of this enrollment
	 */
	public void setClearinghouses(String clearinghouses);

	/**
	 * Returns the ehr billing vendors of this enrollment.
	 *
	 * @return the ehr billing vendors of this enrollment
	 */
	@AutoEscape
	public String getEhrBillingVendors();

	/**
	 * Sets the ehr billing vendors of this enrollment.
	 *
	 * @param ehrBillingVendors the ehr billing vendors of this enrollment
	 */
	public void setEhrBillingVendors(String ehrBillingVendors);

	/**
	 * Returns the rev cycle vendors of this enrollment.
	 *
	 * @return the rev cycle vendors of this enrollment
	 */
	@AutoEscape
	public String getRevCycleVendors();

	/**
	 * Sets the rev cycle vendors of this enrollment.
	 *
	 * @param revCycleVendors the rev cycle vendors of this enrollment
	 */
	public void setRevCycleVendors(String revCycleVendors);

	/**
	 * Returns the top5 drg by rev of this enrollment.
	 *
	 * @return the top5 drg by rev of this enrollment
	 */
	@AutoEscape
	public String getTop5DrgByRev();

	/**
	 * Sets the top5 drg by rev of this enrollment.
	 *
	 * @param top5DrgByRev the top5 drg by rev of this enrollment
	 */
	public void setTop5DrgByRev(String top5DrgByRev);

	/**
	 * Returns the icd9 drg1 of this enrollment.
	 *
	 * @return the icd9 drg1 of this enrollment
	 */
	@AutoEscape
	public String getIcd9Drg1();

	/**
	 * Sets the icd9 drg1 of this enrollment.
	 *
	 * @param icd9Drg1 the icd9 drg1 of this enrollment
	 */
	public void setIcd9Drg1(String icd9Drg1);

	/**
	 * Returns the icd9 drg2 of this enrollment.
	 *
	 * @return the icd9 drg2 of this enrollment
	 */
	@AutoEscape
	public String getIcd9Drg2();

	/**
	 * Sets the icd9 drg2 of this enrollment.
	 *
	 * @param icd9Drg2 the icd9 drg2 of this enrollment
	 */
	public void setIcd9Drg2(String icd9Drg2);

	/**
	 * Returns the icd9 drg3 of this enrollment.
	 *
	 * @return the icd9 drg3 of this enrollment
	 */
	@AutoEscape
	public String getIcd9Drg3();

	/**
	 * Sets the icd9 drg3 of this enrollment.
	 *
	 * @param icd9Drg3 the icd9 drg3 of this enrollment
	 */
	public void setIcd9Drg3(String icd9Drg3);

	/**
	 * Returns the icd9 drg4 of this enrollment.
	 *
	 * @return the icd9 drg4 of this enrollment
	 */
	@AutoEscape
	public String getIcd9Drg4();

	/**
	 * Sets the icd9 drg4 of this enrollment.
	 *
	 * @param icd9Drg4 the icd9 drg4 of this enrollment
	 */
	public void setIcd9Drg4(String icd9Drg4);

	/**
	 * Returns the icd9 drg5 of this enrollment.
	 *
	 * @return the icd9 drg5 of this enrollment
	 */
	@AutoEscape
	public String getIcd9Drg5();

	/**
	 * Sets the icd9 drg5 of this enrollment.
	 *
	 * @param icd9Drg5 the icd9 drg5 of this enrollment
	 */
	public void setIcd9Drg5(String icd9Drg5);

	/**
	 * Returns the top5 icd9 by rev of this enrollment.
	 *
	 * @return the top5 icd9 by rev of this enrollment
	 */
	@AutoEscape
	public String getTop5Icd9ByRev();

	/**
	 * Sets the top5 icd9 by rev of this enrollment.
	 *
	 * @param top5Icd9ByRev the top5 icd9 by rev of this enrollment
	 */
	public void setTop5Icd9ByRev(String top5Icd9ByRev);

	/**
	 * Returns the icd9 dx1 of this enrollment.
	 *
	 * @return the icd9 dx1 of this enrollment
	 */
	@AutoEscape
	public String getIcd9Dx1();

	/**
	 * Sets the icd9 dx1 of this enrollment.
	 *
	 * @param icd9Dx1 the icd9 dx1 of this enrollment
	 */
	public void setIcd9Dx1(String icd9Dx1);

	/**
	 * Returns the icd9 dx2 of this enrollment.
	 *
	 * @return the icd9 dx2 of this enrollment
	 */
	@AutoEscape
	public String getIcd9Dx2();

	/**
	 * Sets the icd9 dx2 of this enrollment.
	 *
	 * @param icd9Dx2 the icd9 dx2 of this enrollment
	 */
	public void setIcd9Dx2(String icd9Dx2);

	/**
	 * Returns the icd9 dx3 of this enrollment.
	 *
	 * @return the icd9 dx3 of this enrollment
	 */
	@AutoEscape
	public String getIcd9Dx3();

	/**
	 * Sets the icd9 dx3 of this enrollment.
	 *
	 * @param icd9Dx3 the icd9 dx3 of this enrollment
	 */
	public void setIcd9Dx3(String icd9Dx3);

	/**
	 * Returns the icd9 dx4 of this enrollment.
	 *
	 * @return the icd9 dx4 of this enrollment
	 */
	@AutoEscape
	public String getIcd9Dx4();

	/**
	 * Sets the icd9 dx4 of this enrollment.
	 *
	 * @param icd9Dx4 the icd9 dx4 of this enrollment
	 */
	public void setIcd9Dx4(String icd9Dx4);

	/**
	 * Returns the icd9 dx5 of this enrollment.
	 *
	 * @return the icd9 dx5 of this enrollment
	 */
	@AutoEscape
	public String getIcd9Dx5();

	/**
	 * Sets the icd9 dx5 of this enrollment.
	 *
	 * @param icd9Dx5 the icd9 dx5 of this enrollment
	 */
	public void setIcd9Dx5(String icd9Dx5);

	/**
	 * Returns the primary testing contact of this enrollment.
	 *
	 * @return the primary testing contact of this enrollment
	 */
	@AutoEscape
	public String getPrimaryTestingContact();

	/**
	 * Sets the primary testing contact of this enrollment.
	 *
	 * @param primaryTestingContact the primary testing contact of this enrollment
	 */
	public void setPrimaryTestingContact(String primaryTestingContact);

	/**
	 * Returns the primary testing contact title of this enrollment.
	 *
	 * @return the primary testing contact title of this enrollment
	 */
	@AutoEscape
	public String getPrimaryTestingContactTitle();

	/**
	 * Sets the primary testing contact title of this enrollment.
	 *
	 * @param primaryTestingContactTitle the primary testing contact title of this enrollment
	 */
	public void setPrimaryTestingContactTitle(String primaryTestingContactTitle);

	/**
	 * Returns the primary testing contact phone of this enrollment.
	 *
	 * @return the primary testing contact phone of this enrollment
	 */
	@AutoEscape
	public String getPrimaryTestingContactPhone();

	/**
	 * Sets the primary testing contact phone of this enrollment.
	 *
	 * @param primaryTestingContactPhone the primary testing contact phone of this enrollment
	 */
	public void setPrimaryTestingContactPhone(String primaryTestingContactPhone);

	/**
	 * Returns the primary testing contact email of this enrollment.
	 *
	 * @return the primary testing contact email of this enrollment
	 */
	@AutoEscape
	public String getPrimaryTestingContactEmail();

	/**
	 * Sets the primary testing contact email of this enrollment.
	 *
	 * @param primaryTestingContactEmail the primary testing contact email of this enrollment
	 */
	public void setPrimaryTestingContactEmail(String primaryTestingContactEmail);

	/**
	 * Returns the primary coding contact of this enrollment.
	 *
	 * @return the primary coding contact of this enrollment
	 */
	@AutoEscape
	public String getPrimaryCodingContact();

	/**
	 * Sets the primary coding contact of this enrollment.
	 *
	 * @param primaryCodingContact the primary coding contact of this enrollment
	 */
	public void setPrimaryCodingContact(String primaryCodingContact);

	/**
	 * Returns the primary coding contact title of this enrollment.
	 *
	 * @return the primary coding contact title of this enrollment
	 */
	@AutoEscape
	public String getPrimaryCodingContactTitle();

	/**
	 * Sets the primary coding contact title of this enrollment.
	 *
	 * @param primaryCodingContactTitle the primary coding contact title of this enrollment
	 */
	public void setPrimaryCodingContactTitle(String primaryCodingContactTitle);

	/**
	 * Returns the primary coding contact phone of this enrollment.
	 *
	 * @return the primary coding contact phone of this enrollment
	 */
	@AutoEscape
	public String getPrimaryCodingContactPhone();

	/**
	 * Sets the primary coding contact phone of this enrollment.
	 *
	 * @param primaryCodingContactPhone the primary coding contact phone of this enrollment
	 */
	public void setPrimaryCodingContactPhone(String primaryCodingContactPhone);

	/**
	 * Returns the primary coding contact email of this enrollment.
	 *
	 * @return the primary coding contact email of this enrollment
	 */
	@AutoEscape
	public String getPrimaryCodingContactEmail();

	/**
	 * Sets the primary coding contact email of this enrollment.
	 *
	 * @param primaryCodingContactEmail the primary coding contact email of this enrollment
	 */
	public void setPrimaryCodingContactEmail(String primaryCodingContactEmail);

	/**
	 * Returns the primary billing contact of this enrollment.
	 *
	 * @return the primary billing contact of this enrollment
	 */
	@AutoEscape
	public String getPrimaryBillingContact();

	/**
	 * Sets the primary billing contact of this enrollment.
	 *
	 * @param primaryBillingContact the primary billing contact of this enrollment
	 */
	public void setPrimaryBillingContact(String primaryBillingContact);

	/**
	 * Returns the primary billing contact title of this enrollment.
	 *
	 * @return the primary billing contact title of this enrollment
	 */
	@AutoEscape
	public String getPrimaryBillingContactTitle();

	/**
	 * Sets the primary billing contact title of this enrollment.
	 *
	 * @param primaryBillingContactTitle the primary billing contact title of this enrollment
	 */
	public void setPrimaryBillingContactTitle(String primaryBillingContactTitle);

	/**
	 * Returns the primary billing contact phone of this enrollment.
	 *
	 * @return the primary billing contact phone of this enrollment
	 */
	@AutoEscape
	public String getPrimaryBillingContactPhone();

	/**
	 * Sets the primary billing contact phone of this enrollment.
	 *
	 * @param primaryBillingContactPhone the primary billing contact phone of this enrollment
	 */
	public void setPrimaryBillingContactPhone(String primaryBillingContactPhone);

	/**
	 * Returns the primary billing contact email of this enrollment.
	 *
	 * @return the primary billing contact email of this enrollment
	 */
	@AutoEscape
	public String getPrimaryBillingContactEmail();

	/**
	 * Sets the primary billing contact email of this enrollment.
	 *
	 * @param primaryBillingContactEmail the primary billing contact email of this enrollment
	 */
	public void setPrimaryBillingContactEmail(String primaryBillingContactEmail);

	/**
	 * Returns the file of this enrollment.
	 *
	 * @return the file of this enrollment
	 */
	@AutoEscape
	public String getFile();

	/**
	 * Sets the file of this enrollment.
	 *
	 * @param file the file of this enrollment
	 */
	public void setFile(String file);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Enrollment enrollment);

	public int hashCode();

	public CacheModel<Enrollment> toCacheModel();

	public Enrollment toEscapedModel();

	public String toString();

	public String toXmlString();
}