/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.virtusa.icd.service.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MedicalRecord service. Represents a row in the &quot;ICD_MedicalRecord&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.virtusa.icd.service.builder.model.impl.MedicalRecordModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.virtusa.icd.service.builder.model.impl.MedicalRecordImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MedicalRecord
 * @see com.virtusa.icd.service.builder.model.impl.MedicalRecordImpl
 * @see com.virtusa.icd.service.builder.model.impl.MedicalRecordModelImpl
 * @generated
 */
public interface MedicalRecordModel extends BaseModel<MedicalRecord>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a medical record model instance should use the {@link MedicalRecord} interface instead.
	 */

	/**
	 * Returns the primary key of this medical record.
	 *
	 * @return the primary key of this medical record
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this medical record.
	 *
	 * @param primaryKey the primary key of this medical record
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mr ID of this medical record.
	 *
	 * @return the mr ID of this medical record
	 */
	public long getMrId();

	/**
	 * Sets the mr ID of this medical record.
	 *
	 * @param mrId the mr ID of this medical record
	 */
	public void setMrId(long mrId);

	/**
	 * Returns the group ID of this medical record.
	 *
	 * @return the group ID of this medical record
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this medical record.
	 *
	 * @param groupId the group ID of this medical record
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this medical record.
	 *
	 * @return the company ID of this medical record
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this medical record.
	 *
	 * @param companyId the company ID of this medical record
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this medical record.
	 *
	 * @return the user ID of this medical record
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this medical record.
	 *
	 * @param userId the user ID of this medical record
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this medical record.
	 *
	 * @return the user uuid of this medical record
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this medical record.
	 *
	 * @param userUuid the user uuid of this medical record
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this medical record.
	 *
	 * @return the user name of this medical record
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this medical record.
	 *
	 * @param userName the user name of this medical record
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this medical record.
	 *
	 * @return the create date of this medical record
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this medical record.
	 *
	 * @param createDate the create date of this medical record
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this medical record.
	 *
	 * @return the modified date of this medical record
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this medical record.
	 *
	 * @param modifiedDate the modified date of this medical record
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the mr test case name of this medical record.
	 *
	 * @return the mr test case name of this medical record
	 */
	@AutoEscape
	public String getMrTestCaseName();

	/**
	 * Sets the mr test case name of this medical record.
	 *
	 * @param mrTestCaseName the mr test case name of this medical record
	 */
	public void setMrTestCaseName(String mrTestCaseName);

	/**
	 * Returns the ms drg of this medical record.
	 *
	 * @return the ms drg of this medical record
	 */
	@AutoEscape
	public String getMsDrg();

	/**
	 * Sets the ms drg of this medical record.
	 *
	 * @param msDrg the ms drg of this medical record
	 */
	public void setMsDrg(String msDrg);

	/**
	 * Returns the patient type of this medical record.
	 *
	 * @return the patient type of this medical record
	 */
	@AutoEscape
	public String getPatientType();

	/**
	 * Sets the patient type of this medical record.
	 *
	 * @param patientType the patient type of this medical record
	 */
	public void setPatientType(String patientType);

	/**
	 * Returns the patient age of this medical record.
	 *
	 * @return the patient age of this medical record
	 */
	@AutoEscape
	public String getPatientAge();

	/**
	 * Sets the patient age of this medical record.
	 *
	 * @param patientAge the patient age of this medical record
	 */
	public void setPatientAge(String patientAge);

	/**
	 * Returns the los of this medical record.
	 *
	 * @return the los of this medical record
	 */
	@AutoEscape
	public String getLos();

	/**
	 * Sets the los of this medical record.
	 *
	 * @param los the los of this medical record
	 */
	public void setLos(String los);

	/**
	 * Returns the ahrq category code of this medical record.
	 *
	 * @return the ahrq category code of this medical record
	 */
	@AutoEscape
	public String getAhrqCategoryCode();

	/**
	 * Sets the ahrq category code of this medical record.
	 *
	 * @param ahrqCategoryCode the ahrq category code of this medical record
	 */
	public void setAhrqCategoryCode(String ahrqCategoryCode);

	/**
	 * Returns the ahrq sub category code of this medical record.
	 *
	 * @return the ahrq sub category code of this medical record
	 */
	@AutoEscape
	public String getAhrqSubCategoryCode();

	/**
	 * Sets the ahrq sub category code of this medical record.
	 *
	 * @param ahrqSubCategoryCode the ahrq sub category code of this medical record
	 */
	public void setAhrqSubCategoryCode(String ahrqSubCategoryCode);

	/**
	 * Returns the mr test case description of this medical record.
	 *
	 * @return the mr test case description of this medical record
	 */
	@AutoEscape
	public String getMrTestCaseDescription();

	/**
	 * Sets the mr test case description of this medical record.
	 *
	 * @param mrTestCaseDescription the mr test case description of this medical record
	 */
	public void setMrTestCaseDescription(String mrTestCaseDescription);

	/**
	 * Returns the icd9 admitting dx of this medical record.
	 *
	 * @return the icd9 admitting dx of this medical record
	 */
	@AutoEscape
	public String getIcd9AdmittingDx();

	/**
	 * Sets the icd9 admitting dx of this medical record.
	 *
	 * @param icd9AdmittingDx the icd9 admitting dx of this medical record
	 */
	public void setIcd9AdmittingDx(String icd9AdmittingDx);

	/**
	 * Returns the icd9 principal dx of this medical record.
	 *
	 * @return the icd9 principal dx of this medical record
	 */
	@AutoEscape
	public String getIcd9PrincipalDx();

	/**
	 * Sets the icd9 principal dx of this medical record.
	 *
	 * @param icd9PrincipalDx the icd9 principal dx of this medical record
	 */
	public void setIcd9PrincipalDx(String icd9PrincipalDx);

	/**
	 * Returns the icd9 principal procedure of this medical record.
	 *
	 * @return the icd9 principal procedure of this medical record
	 */
	@AutoEscape
	public String getIcd9PrincipalProcedure();

	/**
	 * Sets the icd9 principal procedure of this medical record.
	 *
	 * @param icd9PrincipalProcedure the icd9 principal procedure of this medical record
	 */
	public void setIcd9PrincipalProcedure(String icd9PrincipalProcedure);

	/**
	 * Returns the other icd9 dx1 of this medical record.
	 *
	 * @return the other icd9 dx1 of this medical record
	 */
	@AutoEscape
	public String getOtherIcd9Dx1();

	/**
	 * Sets the other icd9 dx1 of this medical record.
	 *
	 * @param otherIcd9Dx1 the other icd9 dx1 of this medical record
	 */
	public void setOtherIcd9Dx1(String otherIcd9Dx1);

	/**
	 * Returns the other icd9 dx2 of this medical record.
	 *
	 * @return the other icd9 dx2 of this medical record
	 */
	@AutoEscape
	public String getOtherIcd9Dx2();

	/**
	 * Sets the other icd9 dx2 of this medical record.
	 *
	 * @param otherIcd9Dx2 the other icd9 dx2 of this medical record
	 */
	public void setOtherIcd9Dx2(String otherIcd9Dx2);

	/**
	 * Returns the other icd9 dx3 of this medical record.
	 *
	 * @return the other icd9 dx3 of this medical record
	 */
	@AutoEscape
	public String getOtherIcd9Dx3();

	/**
	 * Sets the other icd9 dx3 of this medical record.
	 *
	 * @param otherIcd9Dx3 the other icd9 dx3 of this medical record
	 */
	public void setOtherIcd9Dx3(String otherIcd9Dx3);

	/**
	 * Returns the other icd9 pcs1 of this medical record.
	 *
	 * @return the other icd9 pcs1 of this medical record
	 */
	@AutoEscape
	public String getOtherIcd9Pcs1();

	/**
	 * Sets the other icd9 pcs1 of this medical record.
	 *
	 * @param otherIcd9Pcs1 the other icd9 pcs1 of this medical record
	 */
	public void setOtherIcd9Pcs1(String otherIcd9Pcs1);

	/**
	 * Returns the other icd9 pcs2 of this medical record.
	 *
	 * @return the other icd9 pcs2 of this medical record
	 */
	@AutoEscape
	public String getOtherIcd9Pcs2();

	/**
	 * Sets the other icd9 pcs2 of this medical record.
	 *
	 * @param otherIcd9Pcs2 the other icd9 pcs2 of this medical record
	 */
	public void setOtherIcd9Pcs2(String otherIcd9Pcs2);

	/**
	 * Returns the other icd9 pcs3 of this medical record.
	 *
	 * @return the other icd9 pcs3 of this medical record
	 */
	@AutoEscape
	public String getOtherIcd9Pcs3();

	/**
	 * Sets the other icd9 pcs3 of this medical record.
	 *
	 * @param otherIcd9Pcs3 the other icd9 pcs3 of this medical record
	 */
	public void setOtherIcd9Pcs3(String otherIcd9Pcs3);

	/**
	 * Returns the icd10 admitting dx of this medical record.
	 *
	 * @return the icd10 admitting dx of this medical record
	 */
	@AutoEscape
	public String getIcd10AdmittingDx();

	/**
	 * Sets the icd10 admitting dx of this medical record.
	 *
	 * @param icd10AdmittingDx the icd10 admitting dx of this medical record
	 */
	public void setIcd10AdmittingDx(String icd10AdmittingDx);

	/**
	 * Returns the icd10 principal dx of this medical record.
	 *
	 * @return the icd10 principal dx of this medical record
	 */
	@AutoEscape
	public String getIcd10PrincipalDx();

	/**
	 * Sets the icd10 principal dx of this medical record.
	 *
	 * @param icd10PrincipalDx the icd10 principal dx of this medical record
	 */
	public void setIcd10PrincipalDx(String icd10PrincipalDx);

	/**
	 * Returns the icd10 principal procedure of this medical record.
	 *
	 * @return the icd10 principal procedure of this medical record
	 */
	@AutoEscape
	public String getIcd10PrincipalProcedure();

	/**
	 * Sets the icd10 principal procedure of this medical record.
	 *
	 * @param icd10PrincipalProcedure the icd10 principal procedure of this medical record
	 */
	public void setIcd10PrincipalProcedure(String icd10PrincipalProcedure);

	/**
	 * Returns the other icd10 dx1 of this medical record.
	 *
	 * @return the other icd10 dx1 of this medical record
	 */
	@AutoEscape
	public String getOtherIcd10Dx1();

	/**
	 * Sets the other icd10 dx1 of this medical record.
	 *
	 * @param otherIcd10Dx1 the other icd10 dx1 of this medical record
	 */
	public void setOtherIcd10Dx1(String otherIcd10Dx1);

	/**
	 * Returns the other icd10 dx2 of this medical record.
	 *
	 * @return the other icd10 dx2 of this medical record
	 */
	@AutoEscape
	public String getOtherIcd10Dx2();

	/**
	 * Sets the other icd10 dx2 of this medical record.
	 *
	 * @param otherIcd10Dx2 the other icd10 dx2 of this medical record
	 */
	public void setOtherIcd10Dx2(String otherIcd10Dx2);

	/**
	 * Returns the other icd10 dx3 of this medical record.
	 *
	 * @return the other icd10 dx3 of this medical record
	 */
	@AutoEscape
	public String getOtherIcd10Dx3();

	/**
	 * Sets the other icd10 dx3 of this medical record.
	 *
	 * @param otherIcd10Dx3 the other icd10 dx3 of this medical record
	 */
	public void setOtherIcd10Dx3(String otherIcd10Dx3);

	/**
	 * Returns the other icd10 pcs1 of this medical record.
	 *
	 * @return the other icd10 pcs1 of this medical record
	 */
	@AutoEscape
	public String getOtherIcd10Pcs1();

	/**
	 * Sets the other icd10 pcs1 of this medical record.
	 *
	 * @param otherIcd10Pcs1 the other icd10 pcs1 of this medical record
	 */
	public void setOtherIcd10Pcs1(String otherIcd10Pcs1);

	/**
	 * Returns the other icd10 pcs2 of this medical record.
	 *
	 * @return the other icd10 pcs2 of this medical record
	 */
	@AutoEscape
	public String getOtherIcd10Pcs2();

	/**
	 * Sets the other icd10 pcs2 of this medical record.
	 *
	 * @param otherIcd10Pcs2 the other icd10 pcs2 of this medical record
	 */
	public void setOtherIcd10Pcs2(String otherIcd10Pcs2);

	/**
	 * Returns the other icd10 pcs3 of this medical record.
	 *
	 * @return the other icd10 pcs3 of this medical record
	 */
	@AutoEscape
	public String getOtherIcd10Pcs3();

	/**
	 * Sets the other icd10 pcs3 of this medical record.
	 *
	 * @param otherIcd10Pcs3 the other icd10 pcs3 of this medical record
	 */
	public void setOtherIcd10Pcs3(String otherIcd10Pcs3);

	/**
	 * Returns the is history and psysical of this medical record.
	 *
	 * @return the is history and psysical of this medical record
	 */
	public boolean getIsHistoryAndPsysical();

	/**
	 * Returns <code>true</code> if this medical record is is history and psysical.
	 *
	 * @return <code>true</code> if this medical record is is history and psysical; <code>false</code> otherwise
	 */
	public boolean isIsHistoryAndPsysical();

	/**
	 * Sets whether this medical record is is history and psysical.
	 *
	 * @param isHistoryAndPsysical the is history and psysical of this medical record
	 */
	public void setIsHistoryAndPsysical(boolean isHistoryAndPsysical);

	/**
	 * Returns the is discharge notes of this medical record.
	 *
	 * @return the is discharge notes of this medical record
	 */
	public boolean getIsDischargeNotes();

	/**
	 * Returns <code>true</code> if this medical record is is discharge notes.
	 *
	 * @return <code>true</code> if this medical record is is discharge notes; <code>false</code> otherwise
	 */
	public boolean isIsDischargeNotes();

	/**
	 * Sets whether this medical record is is discharge notes.
	 *
	 * @param isDischargeNotes the is discharge notes of this medical record
	 */
	public void setIsDischargeNotes(boolean isDischargeNotes);

	/**
	 * Returns the is consultations of this medical record.
	 *
	 * @return the is consultations of this medical record
	 */
	public boolean getIsConsultations();

	/**
	 * Returns <code>true</code> if this medical record is is consultations.
	 *
	 * @return <code>true</code> if this medical record is is consultations; <code>false</code> otherwise
	 */
	public boolean isIsConsultations();

	/**
	 * Sets whether this medical record is is consultations.
	 *
	 * @param isConsultations the is consultations of this medical record
	 */
	public void setIsConsultations(boolean isConsultations);

	/**
	 * Returns the is operating notes of this medical record.
	 *
	 * @return the is operating notes of this medical record
	 */
	public boolean getIsOperatingNotes();

	/**
	 * Returns <code>true</code> if this medical record is is operating notes.
	 *
	 * @return <code>true</code> if this medical record is is operating notes; <code>false</code> otherwise
	 */
	public boolean isIsOperatingNotes();

	/**
	 * Sets whether this medical record is is operating notes.
	 *
	 * @param isOperatingNotes the is operating notes of this medical record
	 */
	public void setIsOperatingNotes(boolean isOperatingNotes);

	/**
	 * Returns the is physician notes of this medical record.
	 *
	 * @return the is physician notes of this medical record
	 */
	public boolean getIsPhysicianNotes();

	/**
	 * Returns <code>true</code> if this medical record is is physician notes.
	 *
	 * @return <code>true</code> if this medical record is is physician notes; <code>false</code> otherwise
	 */
	public boolean isIsPhysicianNotes();

	/**
	 * Sets whether this medical record is is physician notes.
	 *
	 * @param isPhysicianNotes the is physician notes of this medical record
	 */
	public void setIsPhysicianNotes(boolean isPhysicianNotes);

	/**
	 * Returns the is radiology of this medical record.
	 *
	 * @return the is radiology of this medical record
	 */
	public boolean getIsRadiology();

	/**
	 * Returns <code>true</code> if this medical record is is radiology.
	 *
	 * @return <code>true</code> if this medical record is is radiology; <code>false</code> otherwise
	 */
	public boolean isIsRadiology();

	/**
	 * Sets whether this medical record is is radiology.
	 *
	 * @param isRadiology the is radiology of this medical record
	 */
	public void setIsRadiology(boolean isRadiology);

	/**
	 * Returns the is gi procedures of this medical record.
	 *
	 * @return the is gi procedures of this medical record
	 */
	public boolean getIsGiProcedures();

	/**
	 * Returns <code>true</code> if this medical record is is gi procedures.
	 *
	 * @return <code>true</code> if this medical record is is gi procedures; <code>false</code> otherwise
	 */
	public boolean isIsGiProcedures();

	/**
	 * Sets whether this medical record is is gi procedures.
	 *
	 * @param isGiProcedures the is gi procedures of this medical record
	 */
	public void setIsGiProcedures(boolean isGiProcedures);

	/**
	 * Returns the is educational notes of this medical record.
	 *
	 * @return the is educational notes of this medical record
	 */
	public boolean getIsEducationalNotes();

	/**
	 * Returns <code>true</code> if this medical record is is educational notes.
	 *
	 * @return <code>true</code> if this medical record is is educational notes; <code>false</code> otherwise
	 */
	public boolean isIsEducationalNotes();

	/**
	 * Sets whether this medical record is is educational notes.
	 *
	 * @param isEducationalNotes the is educational notes of this medical record
	 */
	public void setIsEducationalNotes(boolean isEducationalNotes);

	/**
	 * Returns the file of this medical record.
	 *
	 * @return the file of this medical record
	 */
	@AutoEscape
	public String getFile();

	/**
	 * Sets the file of this medical record.
	 *
	 * @param file the file of this medical record
	 */
	public void setFile(String file);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(MedicalRecord medicalRecord);

	public int hashCode();

	public CacheModel<MedicalRecord> toCacheModel();

	public MedicalRecord toEscapedModel();

	public String toString();

	public String toXmlString();
}