/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.virtusa.icd.service.builder.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.virtusa.icd.service.builder.model.Enrollment;
import com.virtusa.icd.service.builder.service.EnrollmentLocalService;
import com.virtusa.icd.service.builder.service.EnrollmentService;
import com.virtusa.icd.service.builder.service.ReferencesLocalService;
import com.virtusa.icd.service.builder.service.ReferencesService;
import com.virtusa.icd.service.builder.service.persistence.EnrollmentPersistence;
import com.virtusa.icd.service.builder.service.persistence.ReferencesPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the enrollment local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.virtusa.icd.service.builder.service.impl.EnrollmentLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.virtusa.icd.service.builder.service.impl.EnrollmentLocalServiceImpl
 * @see com.virtusa.icd.service.builder.service.EnrollmentLocalServiceUtil
 * @generated
 */
public abstract class EnrollmentLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements EnrollmentLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.virtusa.icd.service.builder.service.EnrollmentLocalServiceUtil} to access the enrollment local service.
	 */

	/**
	 * Adds the enrollment to the database. Also notifies the appropriate model listeners.
	 *
	 * @param enrollment the enrollment
	 * @return the enrollment that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Enrollment addEnrollment(Enrollment enrollment)
		throws SystemException {
		enrollment.setNew(true);

		return enrollmentPersistence.update(enrollment, false);
	}

	/**
	 * Creates a new enrollment with the primary key. Does not add the enrollment to the database.
	 *
	 * @param enrollmentId the primary key for the new enrollment
	 * @return the new enrollment
	 */
	public Enrollment createEnrollment(long enrollmentId) {
		return enrollmentPersistence.create(enrollmentId);
	}

	/**
	 * Deletes the enrollment with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param enrollmentId the primary key of the enrollment
	 * @return the enrollment that was removed
	 * @throws PortalException if a enrollment with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public Enrollment deleteEnrollment(long enrollmentId)
		throws PortalException, SystemException {
		return enrollmentPersistence.remove(enrollmentId);
	}

	/**
	 * Deletes the enrollment from the database. Also notifies the appropriate model listeners.
	 *
	 * @param enrollment the enrollment
	 * @return the enrollment that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public Enrollment deleteEnrollment(Enrollment enrollment)
		throws SystemException {
		return enrollmentPersistence.remove(enrollment);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Enrollment.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return enrollmentPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return enrollmentPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return enrollmentPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return enrollmentPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public Enrollment fetchEnrollment(long enrollmentId)
		throws SystemException {
		return enrollmentPersistence.fetchByPrimaryKey(enrollmentId);
	}

	/**
	 * Returns the enrollment with the primary key.
	 *
	 * @param enrollmentId the primary key of the enrollment
	 * @return the enrollment
	 * @throws PortalException if a enrollment with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public Enrollment getEnrollment(long enrollmentId)
		throws PortalException, SystemException {
		return enrollmentPersistence.findByPrimaryKey(enrollmentId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return enrollmentPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the enrollments.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of enrollments
	 * @param end the upper bound of the range of enrollments (not inclusive)
	 * @return the range of enrollments
	 * @throws SystemException if a system exception occurred
	 */
	public List<Enrollment> getEnrollments(int start, int end)
		throws SystemException {
		return enrollmentPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of enrollments.
	 *
	 * @return the number of enrollments
	 * @throws SystemException if a system exception occurred
	 */
	public int getEnrollmentsCount() throws SystemException {
		return enrollmentPersistence.countAll();
	}

	/**
	 * Updates the enrollment in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param enrollment the enrollment
	 * @return the enrollment that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Enrollment updateEnrollment(Enrollment enrollment)
		throws SystemException {
		return updateEnrollment(enrollment, true);
	}

	/**
	 * Updates the enrollment in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param enrollment the enrollment
	 * @param merge whether to merge the enrollment with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the enrollment that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Enrollment updateEnrollment(Enrollment enrollment, boolean merge)
		throws SystemException {
		enrollment.setNew(false);

		return enrollmentPersistence.update(enrollment, merge);
	}

	/**
	 * Returns the enrollment local service.
	 *
	 * @return the enrollment local service
	 */
	public EnrollmentLocalService getEnrollmentLocalService() {
		return enrollmentLocalService;
	}

	/**
	 * Sets the enrollment local service.
	 *
	 * @param enrollmentLocalService the enrollment local service
	 */
	public void setEnrollmentLocalService(
		EnrollmentLocalService enrollmentLocalService) {
		this.enrollmentLocalService = enrollmentLocalService;
	}

	/**
	 * Returns the enrollment remote service.
	 *
	 * @return the enrollment remote service
	 */
	public EnrollmentService getEnrollmentService() {
		return enrollmentService;
	}

	/**
	 * Sets the enrollment remote service.
	 *
	 * @param enrollmentService the enrollment remote service
	 */
	public void setEnrollmentService(EnrollmentService enrollmentService) {
		this.enrollmentService = enrollmentService;
	}

	/**
	 * Returns the enrollment persistence.
	 *
	 * @return the enrollment persistence
	 */
	public EnrollmentPersistence getEnrollmentPersistence() {
		return enrollmentPersistence;
	}

	/**
	 * Sets the enrollment persistence.
	 *
	 * @param enrollmentPersistence the enrollment persistence
	 */
	public void setEnrollmentPersistence(
		EnrollmentPersistence enrollmentPersistence) {
		this.enrollmentPersistence = enrollmentPersistence;
	}

	/**
	 * Returns the references local service.
	 *
	 * @return the references local service
	 */
	public ReferencesLocalService getReferencesLocalService() {
		return referencesLocalService;
	}

	/**
	 * Sets the references local service.
	 *
	 * @param referencesLocalService the references local service
	 */
	public void setReferencesLocalService(
		ReferencesLocalService referencesLocalService) {
		this.referencesLocalService = referencesLocalService;
	}

	/**
	 * Returns the references remote service.
	 *
	 * @return the references remote service
	 */
	public ReferencesService getReferencesService() {
		return referencesService;
	}

	/**
	 * Sets the references remote service.
	 *
	 * @param referencesService the references remote service
	 */
	public void setReferencesService(ReferencesService referencesService) {
		this.referencesService = referencesService;
	}

	/**
	 * Returns the references persistence.
	 *
	 * @return the references persistence
	 */
	public ReferencesPersistence getReferencesPersistence() {
		return referencesPersistence;
	}

	/**
	 * Sets the references persistence.
	 *
	 * @param referencesPersistence the references persistence
	 */
	public void setReferencesPersistence(
		ReferencesPersistence referencesPersistence) {
		this.referencesPersistence = referencesPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.virtusa.icd.service.builder.model.Enrollment",
			enrollmentLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.virtusa.icd.service.builder.model.Enrollment");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return Enrollment.class;
	}

	protected String getModelClassName() {
		return Enrollment.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = enrollmentPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = EnrollmentLocalService.class)
	protected EnrollmentLocalService enrollmentLocalService;
	@BeanReference(type = EnrollmentService.class)
	protected EnrollmentService enrollmentService;
	@BeanReference(type = EnrollmentPersistence.class)
	protected EnrollmentPersistence enrollmentPersistence;
	@BeanReference(type = ReferencesLocalService.class)
	protected ReferencesLocalService referencesLocalService;
	@BeanReference(type = ReferencesService.class)
	protected ReferencesService referencesService;
	@BeanReference(type = ReferencesPersistence.class)
	protected ReferencesPersistence referencesPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private EnrollmentLocalServiceClpInvoker _clpInvoker = new EnrollmentLocalServiceClpInvoker();
}